/*
 *
 * SignIn constants
 *
 */

export const ACTIONS = {
	SIGN_IN_ATTEMPT: 'SIGN_IN_ATTEMPT',
	SIGN_IN_FAILED: 'SIGN_IN_FAILED',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',

	SIGN_UP_ATTEMPT: 'SIGN_UP_ATTEMPT',
	SIGN_UP_FAILED: 'SIGN_UP_FAILED',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
};